version: '3.8'

services:
  podbrief:
    build: .
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
      - PORT=5000
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - DB_PATH=/app/server/data/podbrief.db
    volumes:
      - podbrief_data:/app/server/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:5000/api/health', (res) => { process.exit(res.statusCode === 200 ? 0 : 1) })"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Development service (optional)
  podbrief-dev:
    build: .
    ports:
      - "5001:5000"
    environment:
      - NODE_ENV=development
      - PORT=5000
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - DB_PATH=/app/server/data/podbrief-dev.db
    volumes:
      - podbrief_dev_data:/app/server/data
      - ./server:/app/server
      - ./client:/app/client
    command: npm run dev
    profiles:
      - dev

volumes:
  podbrief_data:
  podbrief_dev_data: 